# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - run: wget "https://snapshots.mitmproxy.org/9.0.1/mitmproxy-9.0.1-linux.tar.gz" -O "/tmp/mitmproxy.tar.gz" -q;mkdir -p "/tmp/mitm";tar -xf "/tmp/mitmproxy.tar.gz" -C "/tmp/mitm";sudo mv "/tmp/mitm/mitmdump" "/usr/local/bin"
    - run: sudo useradd mitmproxyuser;sudo mkdir /home/mitmproxyuser;sudo chown -R mitmproxyuser /home/mitmproxyuser
    - run: sudo -u mitmproxyuser -H sh -c '/usr/local/bin/mitmdump --mode transparent&'
    - run: kill `pidof mitmdump`
    - name: Run
      run: go run main.go
    - run: ls -lah /home/mitmproxyuser
    

